name: projeto_final
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging:
  cloud_firestore: ^0.11.0+2
  firebase_core: any
  cupertino_icons: ^0.1.2
  video_player: ^0.10.2+1
  flutter_bluetooth_serial: ^0.2.2
  scoped_model: ^1.0.1
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

flutter:

  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/launcher/icon.png
    - videos/DemonSlayer.mp4

  uses-material-design: true